### ISSUE TITLE
Code of Conduct file needed 

### ISSUE THREAD

**Issue by CBID2** [amandamartin-dev/women-led-open-source#1]
Hi @amandamartin-dev! I think we need to add some sort of Code of Conduct file, just to keep the space safe for the contributors, especially those who are our core "audience".

**Comment by amandamartin-dev** [comment]
sure! Go for it

**Comment by CBID2** [comment]
> sure! Go for it

Here it [is](https://github.com/amandamartin-dev/women-led-open-source/pull/2) @amandamartin-dev ! Feel free to edit to your liking.
