### ISSUE TITLE
Issue Templates

### ISSUE THREAD

**Issue by CBID2** [amandamartin-dev/women-led-open-source#20]
Hey, @amandamartin-dev! 😄 Since you came up with the idea of letting open source founders request removal upon request, maybe there can be a specific issue template for that(as well as one for resources)?  It'll increase productivity in regard to differentiating requests to add or remove sources.

**Comment by amandamartin-dev** [comment]
Sure sounds good! Let's have a separate issue for each.

**Comment by amandamartin-dev** [comment]
After thinking on this more I think issue tempates for contributors simply creates more work for them as at this time it's onyl required to create a PR against the readme.  Good discussion and perhaps in the future should other kinds of requests come in
