### ISSUE TITLE
Add a resource

### ISSUE THREAD

**Issue by amandamartin-dev** [amandamartin-dev/women-led-open-source#6]
This is the easiest green square you will get today!

All you need to do is add a repo and name resource to the readme that falls under folks identifying as women, transgender people, nonbinary people, and other underrepresented genders leading open source projects and companies, serving as maintainers, or otherwise supporting Open Source.

This issue is evergreen and would benefit from many contributions.  Please comment if you have any questions.

**Comment by goobric** [comment]
hi Amanda, how do I add a name and resource to the readme file?
Thank you

**Comment by amandamartin-dev** [comment]
> hi Amanda, how do I add a name and resource to the readme file?

Hello! To start a pull request to the readme, you will want to follow these steps:

1. click on the little pencil at the top right of the readme file to start some edits
2. add your edits to the file
3. scroll to the bottom and you will see a place where you can title and comment to submit a pull request

Let me know if that is enough information to get started and thank you for contributing!

**Comment by goobric** [comment]
Thank you so much Amanda for the clear instructions, much appreciated.
I have included the Women in Technology link
