### ISSUE TITLE
Add a repo license

### ISSUE THREAD

**Issue by eddiejaoude** [amandamartin-dev/women-led-open-source#9]
https://choosealicense.com

<img width="1359" alt="Screenshot 2023-04-11 at 11 10 52" src="https://user-images.githubusercontent.com/624760/231054119-7d7fa6b4-a3ce-4175-84fb-d91e76abb83f.png">

**Comment by amandamartin-dev** [comment]
Thank you, good idea! I will look at this shortly

**Comment by CBID2** [comment]
> Thank you, good idea! I will look at this shortly

Hey @amandamartin-dev! 😄 I personally think [this license](https://choosealicense.com/non-software/)would best suit the repo since it’s more of a source of information instead of an actual piece of software. What do you think?

**Comment by amandamartin-dev** [comment]
> Hey @amandamartin-dev! 😄 I personally think [this license](https://choosealicense.com/non-software/)would best suit the repo since it’s more of a source of information instead of an actual piece of software. What do you think?

Yes, agreed. What do you think about this one? https://choosealicense.com/licenses/cc0-1.0/

**Comment by CBID2** [comment]
> > Hey @amandamartin-dev! 😄 I personally think [this license](https://choosealicense.com/non-software/)would best suit the repo since it’s more of a source of information instead of an actual piece of software. What do you think?
> 
> Yes, agreed. What do you think about this one? https://choosealicense.com/licenses/cc0-1.0/

I like it! It falls in line with the repo’s mission to be inclusive.
